import cgi
import urllib

from google.appengine.ext import ndb

import webapp2


class Users(ndb.Model):
    un = ndb.StringProperty()
    pw = ndb.StringProperty()
    email = ndb.StringProperty()
    gender = ndb.StringProperty()       # m or f
    description = ndb.StringProperty()
    
    @property
    def pid(self):
        return self.key.id()
    
    @classmethod
    def createNewUser(cls, username, password, email, gender, description):
        user = Users(un=username, pw=password, email=email, gender=gender, description=description)
        
        # put stores data on server
        # returns key of type (Users, id) where id is randomly generated by app engine
        user_key = user.put()
        return user_key
        
class userFunctions():
    pass